package stuscoresystem.sturcture;

public enum Permission {
    ADD_STUDENT, DELETE_STUDENT, UPDATE_STUDENT, GET_STUDENT, ADD_SCORE, UPDATE_SCORE, GET_SCORE,
    CALCULATE_STUDENT_AVG_SCORE, CALCULATE_COURSE_AVG_SCORE, ADD_USER, UPDATE_USER_PASSWORD, UPDATE_USER_ROLE,ADD_SYSTEM_DATA
}
